---
title: "\U0001F4DA Miscellaneous Graphs and Tools "
author: "Arvind Venkatadri"
weight: 110
type: book
subtitle: "Miscellaneous Graphs and Tools"
date: "`r Sys.Date()`"
summary: 
tags:
- Digital Humanities
- Online Tools
- Data Viz Guides
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
external_link: ""
links:
# - icon: linkedin
#   icon_pack: fab
#   name: 
#   url: https://linkedin.com/arvindvenkatadri
# - icon: twitter
#   icon_pack: fab
#   name: 
#   url: https://twitter.com/arvind_v
slides: ""
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)

```

## What other free tools are there on the web?


### RAWGraphs.io
<https://rawgraphs.io>


### DataWrapper
<https://datawrapper.de>


### Palladio

<https://hdlab.stanford.edu/palladio/>


### Infogram
<https://infogram.com/>


### Visme
<https://www.visme.co/chart-maker/>


### Flourish + Figma 
<https://flourish.studio/>
<https://www.figma.com/>


### DisplayR
<https://www.displayr.com/dashboard-examples/>

###



## References

1. *Getting started with Flourish & Figma to create beautiful custom charts*, 
<https://inside.mediahack.co.za/getting-started-with-flourish-figma-to-create-beautiful-custom-charts-34e4efb8fd3d> 

1. Flowing Data Chart Types <https://flowingdata.com/chart-types/>  

1. Geeks for Geeks: Chart Types
<https://www.geeksforgeeks.org/r-charts-and-graphs/>  

1. Financial Times Visual Vocabulary (Interactive)
<https://ft-interactive.github.io/visual-vocabulary/>  

1. Financial Times Visual Vocabulary (PDF)
<https://github.com/Financial-Times/chart-doctor/blob/main/visual-vocabulary/FT4schools_RGS.pdf>  

1. Financial Times Data Journalism Visuals
<https://www.ft.com/visual-and-data-journalism>

1. Severino Ribecca and John Schwabish , *The Graphic Continuum*
<https://www.severinoribecca.one/portfolio-item/the-graphic-continuum/>

1. Web based tools for Dataviz
<https://policyviz.com/resources/data-viz-tools/>  

1. Nightingale Data Visualization Society Blog: **How to visualize categorical data**:
<https://nightingaledvs.com/endless-river-an-overview-of-dataviz-for-categorical-data/>  

1. John Schwabish's *policyviz* Data Viz catalogue:
<https://datastudio.google.com/s/quUUlgosF4U> 

<iframe width="800" height="800" src="https://datastudio.google.com/embed/reporting/eb2fea55-8eeb-440f-9c56-e8278266a368/page/vZWQB" frameborder="0" style="border:0" allowfullscreen></iframe>  



## Papers

1.Christopher G. Healey
Department of Computer Science, North Carolina State University. [Perception in Visualization](https://www.csc2.ncsu.edu/faculty/healey/PP/index.html)  

1. 


