---
title: "\U0001F335 Fractals"
date: "2021-01-24"
type: book
weight: 80
links:
slides: 
summary: An exploration of fractal shape and fractal math!
tags:
- fractals
- Iterated Functions
- Siepinski
- Mandelbrot
- Julia
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

```{r, echo=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)
library(emoji)
#devtools::install_github("mccarthy-m-g/embedr")
library(embedr) # Embed multimedia in HTML files
```

#### A Geometric Jewellery Store

![Photo by <a href="https://unsplash.com/@kolyakorzh?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mykola/Kolya Korzh</a> on <a href="https://unsplash.com/photos/brown-wooden-bird-house-ornament-HFogW6fHv4E?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  ](featured.jpg)


## Introduction

Let us listen to the late great Benoit Mandelbrot, on the **Art of Roughness**.

`r blogdown::shortcode("youtube", "wQTnVEXAtBY")`


## A Little ( just a little?) of Maths...

### What am $i$?
Dude, what's the square root of -1?? `r emoji::emoji("scream_cat")` `r emoji::emoji("scream_cat")` `r emoji::emoji("scream_cat")`

What can you do repeatedly to arrive at $[-1, 0]$?

### Complex Planes

`r blogdown::shortcode("youtube", "t75gXyWJNpA")`

### Julia, and Julia, and still more Julia....

`r blogdown::shortcode("youtube", "2AZYZ-L8m9Q")`


### Jewellery Shopping with Mandelbrot

Ever gone shopping for jewellery? How is the place organized? That is a good metaphor for how Mandelbrot Set is generated!!

`r blogdown::shortcode("youtube", "8ma6cV6fw24")`


## <u>[Wait, But Why?](https://waitbutwhy.com)</u>
To be Written Up. 

## References

1. Menger Sponge: <https://blogs.scientificamerican.com/roots-of-unity/a-few-of-my-favorite-spaces-the-menger-sponge/>

Use XaOS to make Mandelbrot and Julia fractals.

