---
title: "\U0001F578 No Man is an Island"
subtitle: "Part of a Whole"
author: "Arvind Venkatadri"
date: "`r Sys.Date()`"
weight: 50
summary: "Slices, Portions, Counts, and Aggregates of Data"
tags:
- Pie Charts
- Mosaic Charts
- Venn Diagrams
- Tree Charts and Dendrograms
- Parliament and Waffle Charts

image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
external_link: ""
links:
# - icon: linkedin
#   icon_pack: fab
#   name: 
#   url: https://linkedin.com/arvindvenkatadri
# - icon: twitter
#   icon_pack: fab
#   name: 
#   url: https://twitter.com/arvind_v
slides: ""
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)

```

## An Example

What influences love at first sight? (Or, at least, love in the first four minutes?) 

This dataset was compiled by Columbia Business School professors Ray Fisman and Sheena Iyengar for their paper [**Gender Differences in Mate Selection: Evidence From a Speed Dating Experiment**](https://www0.gsb.columbia.edu/mygsb/faculty/research/pubfiles/866/racialPreferences.pdf). 

Data was gathered from participants in experimental speed dating events from 2002-2004. During the events, the attendees would have a four minute "first date" with every other participant of the opposite sex. At the end of their four minutes, participants were asked if they would like to see their date again. They were also asked to rate their date on six attributes: Attractiveness, Sincerity, Intelligence, Fun, Ambition, and Shared Interests.


## What is the Story here?

1. Do people prefer to date someone from their own *race*? 
1. Is that different for men and women?
1. Does physical attractiveness help to overcome age differences?  


