title: The Foundation Series
baseurl: 'https://the-foundation-series.netlify.app'
copyright: ''
theme: starter-hugo-academic
enableGitInfo: true
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
summaryLength: 30
paginate: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
    ignoreErrors: error-remote-getjson
# Params:
#   showRelatedPosts: yes



