---
date: "2021-10-12"
title: Cultural Capital
external_link: ""
weight: 2
image: 
  caption: Photo from Getty Images
  focal_point: Smart
links:
slides: ""
summary: 
tags:
- Pierre Bourdieu
- Cultural Capital
- Habitus
- Embodied CC
- Objectified CC
- Institutionalized CC

url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

# Introduction

We will understand Pierre Bourdieu's Concept of {{<hl>}}Cultural Capital ( CC ){{</hl>}}. 

CC affects our view of the world and helps us identify Problem Situations and Contradictions in Life. These can then become subject to analysis using techniques such as Edward de Bono's Six Thinking Hats and Genrikh Altshuller's TRIZ.

1. **What is Cultural Capital?** [(weblink)](https://culturallearningalliance.org.uk/what-is-cultural-capital)
<br>

2. Cultural Capital <br>
`r blogdown::shortcode("youtube", "5DBEYiBkgp8")`

3. Mhaly Csikszentmihalyi's Systems Model: **Domain, Field and the Creative Person**
[(Weblink)](https://medium.com/call4/domain-8a22b6b486f4)

# Activity

1. Web Apps for your Makey-Makey:  [(Weblink)](https://makeymakey.com/blogs/how-to-instructions/apps-for-plug-and-play)

1. Make your own game with a Makey-Makey: [(Weblink)](https://www.instructables.com/Using-Scratch-and-Makey-Makey-to-make-your-own-gam/)


Assignment:

1. Making a Street Intersection Logo: [(Inspiration)](http://www.cartogrammar.com/blog/maps-make-the-best-logos/). <br> <br>
Here are some instructions:
 - Visit your home town on Google Maps
 - Select a specific STREET INTERSECTION there.
 - Copy paste the Shape of the Street Intersection into your favourite image making software
 - Create A LOGO for your city, using the Shape, such that you show off some interesting aspects of your City, based on your own CULTURAL CAPITAL.
 - Three sentences to describe your Logo.
 - See examples at the link above for inspiration
