---
title: "\U0001F409 Intro to Linear Programming"
author: "Arvind Venkatadri"
date: "`r Sys.Date()`"
linkTitle: Intro to Linear Programming
summary: 
view: 2
weight: 10
---

```{r setup, include=FALSE}
library(blogdown)
library(gMOIP)
# See: https://relund.github.io/gMOIP/index.html
library(knitr)
library(rgl)
rgl::setupKnitr()
options(rgl.useNULL=TRUE)
opts_chunk$set(
  echo = FALSE,
  collapse = TRUE,
  #cache = TRUE, autodep = TRUE, 
  comment = "#>",
  fig.show = "asis", 
  warning=FALSE, message=FALSE, include = TRUE, 
  out.width = "99%", fig.width = 8, fig.align = "center", fig.asp = 0.62
)
```

## Introduction

What is Linear Programming?

## Demonstration of Level Curve

<iframe src="https://www.geogebra.org/classic/xpdx7fae?embed" width="800" height="600" allowfullscreen style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0">

</iframe>

## Linear Programming Solver

<iframe src="https://www.geogebra.org/classic/xdqrtg4m?embed" width="800" height="600" allowfullscreen style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0">

</iframe>

## Linear Programming in 3D view

<iframe width="560" height="315" src="https://www.youtube.com/embed/kPOXqQhCWHs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

## Linear Programming Interactive

Let us say we have a Linear Programming problem with *3* variables: We define the model:

$$
Maximise : 20x_1 + 10x_2 + 15x_3\\
Subject \ to \\
\\
x_1 + x_2 + x_3 <= 10\\
3x_1 + x_3 <= 24 
$$

```{r ex2Model}
A <- matrix( c(
   1, 1, 1,
   3, 0, 1
), nc = 3, byrow = TRUE)
b <- c(10, 24)
obj <- c(20, 10, 15)

```

```{r ex2View}

# We load the preferred view angle for the RGL window:
#
view <- matrix( c(-0.812462985515594, -0.029454167932272, 
                  0.582268416881561, 0, 0.579295456409454,
                  -0.153386667370796, 0.800555109977722, 
                  0, 0.0657325685024261, 0.987727105617523,
                  0.14168381690979, 0, 0, 0, 0, 1), nc = 4)
```

Here is the interactive LP Polytope:

```{r ex2LP, webgl = TRUE}
loadView(v = view, close = T, zoom = 0.75)
plotPolytope(A, b, faces = c("c","c","c"), 
             # type = c("i","i","i"), 
             plotOptimum = TRUE, obj = obj, 
             argsTitle3d = list(main = "Polytope with LP faces"), 
             argsPlot3d = list(box = F, axes = T) )

```

## References

1.  Virginia Postrel, *Operations Everything*, Boston Globe, Hune 27, 2004. <http://archive.boston.com/news/globe/ideas/articles/2004/06/27/operation_everything?pg=full>
