---
date: "2021-10-15"
title: "Divergent Thinking and the 6 Thinking Hats"
external_link: ""
weight: 3
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
links:
slides: ""
summary: 
tags:
- Guilford
- Wallas-Kogan
- Cultural Capital
- Thinking Hats
- Edward de Bono
url_code: ""
url_pdf: "pdf/6H/KS Mathew - Six Thinking Hats.pdf"
url_slides: ""
url_video: ""
---

## Materials

A. **Divergent Thinking**

1. Guilford Test for Divergent Thinking: [(Weblink)](https://curtbonk.com/bobweb/d1.html)

2. Wallas-Kogan Test for Divergent Thinking: [(Weblink)](https://curtbonk.com/bobweb/d2.html)

### Scoring

Scoring is comprised of four components:

Originality - each response it compared to the total amount of responses from all of the people you gave the test to.  Reponses that were given by only 5% of your group are unusual (1 point), responses that were given by only 1% of your group are unique - 2 points).  Total all the point.  Higher scores indicate creativity*
Fluency - total. Just add up all the responses.  In this example it is 6.
Flexibility - or different categories.  In this case there are five different categories (weapon and hit sister are from the same general idea of weapon)
Elaboration - amount of detail (for Example "a doorstop" = 0 whereas "a door stop to prevent a door slamming shut in a strong wind" = 2 (one for explanation of door slamming, two for further detail about the wind).

*You might have noticed that the higher fluency the higher the originality (if you did "good for you!")  This is a contamination problem and can be corrected by using a corrective calculation for originality
(originality = originality/fluency).

B. **Parallel Thinking**

`r blogdown::shortcode("youtube", "uYBaSZYZ3sI")`

Some of the de Bono Thinking Tools: 

1. 6 Thinking Hats Quick Reference [(**PDF Link**)](W1D1 - 01 - The Six Thinking Hats.pdf)

2. 6H Technique - PMI: Plus Minus Interesting : [(**Web Link**)](https://www.cortthinking.com/cort/1/p-m-i-plus-minus-and-interesting-cort-1-lesson-1)

3. 6H Technique - APC: Alternatives, Possibilities, Choices: [(**Web Link**)](https://www.cortthinking.com/cort/1/alternatives-possibilities-choices-cort-1-lesson-8)

4. 6H Technique - CAF: Consider All Factors: [(**Web Link**)](https://www.cortthinking.com/cort/1/caf-consider-all-factors-cort-1-lesson-2)

5. 6H Technique - OPV: Other Peoples' Voices: [(**Web Link**)](https://www.cortthinking.com/cort/1/other-people%E2%80%99s-views-cort-1-lesson-10)

6. 6H Technique - CnS: Consequence and Sequel : [(**Web Link**)](https://www.cortthinking.com/cort/1/cs-consequence-and-sequel-cort-1-lesson-4)

## References

1. Reading in Parallel Thinking [(**Web Link**)](https://www.debonogroup.com/services/core-programs/lateral-thinking/parallel-thinking/)

2. Edward de Bono, Six Thinking Hats [(**Goodreads**)](https://www.goodreads.com/book/show/97030.Six_Thinking_Hats)

3. Bobo Hjort, Drawing, Knowledge, and Intuitive Thinking: 
Drawing as a Way to Understand and Solve Complex Problems in *Art and Complexity*, J. Casti and A. Karlqvist (editors) © 2003 Published by Elsevier Science B.V. 

