---
title: "\U0001F579 Still More Games !!"
author: "Arvind Venkatadri"
date: 2021-12-11
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
weight: 2
---


```{r include=FALSE}
library(blogdown)
```

## Introduction

A brief Introduction to the [**Stag Hunt Game**](https://www.heretical.com/pound/staghunt.html)



### Movie Time!

 <br> `r blogdown::shortcode("youtube", "QQHPDLfbIK4")` <br>



### Coordination Games and Schelling Focus Points 

Watch these two videos on the topic of Focal Points as defined by Schelling.

 <br> `r blogdown::shortcode("youtube", "CFOQquw6hig")` <br>

<br>

 <br> `r blogdown::shortcode("youtube", "oDsePkuaL9Q")` <br>

<br>

Focal points can be used in Coordination Games: these are activities where people's actions tend to organize into Patterns based on specific default options. These actions could be 

a) Conversation

b) Dress

c) Travel / Meeting

d) Location

e) Attention

### Additional Readings on Schelling Points

a) https://mindyourdecisions.com/blog/2008/04/01/focal-points-or-schelling-points-how-we-naturally-organize-in-games-of-coordination/

b) https://medium.com/@richlitt/using-schelling-points-to-perform-better-973243efd989

### The Game of the Polygons

Let us explore, sadly, the `dark side` of Game Theory. Where our own agent-like actions lead to bad outcomes in Society...

Always?

Not if we...choose wisely !!


Let us play **The Game of the Polygons** [(web link)](http://ncase.me/polygons/)


### Another Dark Side of...

Why are Petrol Stations located next to each other? Here is the **Hotelling's Phenomenon**, explained. 

 <br> `r blogdown::shortcode("youtube", "u4cKzGj58q4")` <br>
