---
title: "Data, DataViz, and Stats with the Stars"
format: 
  revealjs: 
    controls: true
    controls-layout: bottom-right
    footer: "Arvind V.| VizChitra2025 | June 2025"
    html-math-method: katex
    include-in-header: 
      - text: '<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>'
###
    webcam: 
      toggleKey: "W" # Change the key to toggle the video
      enabled: false # Enable the video stream directly at startup. Pressing [W] will still allow you to toggle it.
      persistent: false # Keep the stream open (the camera active) after opening it once. If it is enabled the plugin will keep the camera on even if the video is not used. This avoids repeat permission request dialogs.

###
    scrollable: true
    slide-number: true
    show-slide-number: print
    preview-links: auto
    embed-resources: false
    touch: true
    pointer:
      key: "q"
      color: "green"
      pointerSize: 48
      alwaysVisible: false

###
revealjs-plugins:
  - animate-graph
  - revealjs-text-resizer
  - pointer
  - excalidraw
  - webcam
#  - drop # console drop-down # not working at all
#  - spotlight
#  - subtitles # works, but not needed

filters: 
   - highlight-text #colour #bg-colour #fg
   - tachyons
---

## Agenda!

-   Orange? What is this Orange stuff, anyhow?
-   Throwing it All Away with Brad Pitt: Data Summaries
-   Counting Letters with Sherlock Holmes
-   Nursery Rhymes with Ben Affleck: Line Charts
-   Being a Mermaid with Katie Ledecky: Box Plots
-   Jack and Rose lived happily ever after: Mosaic Plots
-   The Art of Surprise with Gabbar Singh: Permutation Tests

::: notes
{{< downloadthis files/mtcars.csv dname="mtcars.csv" label="Download the mtcars data" icon="database-fill-down" type="info" >}}
:::

------------------------------------------------------------------------

## Orange? What is this Orange stuff, anyhow? {.center}

------------------------------------------------------------------------

## Installing and Getting Used to Orange

some stuff here

------------------------------------------------------------------------

## Brad Pitt: Throwing it All Away {.center}

------------------------------------------------------------------------

## Brad Pitt: Throwing it All Away

<center>
{{< video https://youtu.be/PlKDQqKh03Y height=540 width=760 title='None of them!'>}}
</center>

::: notes
Speaker notes go here.
:::

------------------------------------------------------------------------

## Brad Pitt: Throwing it All Away

Steven Stigler (2016) in “The Seven Pillars of Statistical Wisdom”:

-   One of the Big Ideas in Statistics is: Aggregation

> -   How is it revolutionary? By stipulating that, given a number of
>     observations, [you can actually gain information by throwing
>     information away]{.bg-light-red .black}
> -   In taking a simple arithmetic mean, we discard the individuality
>     of the measures, subsuming them to one summary.

------------------------------------------------------------------------

## Brad Pitt: Throwing it All Away
### What was he throwing away?

::::: columns
::: {.column width="45%"}
data table here
:::

::: {.column width="45%"}
"OBP" as aggregate column explanation here
:::
:::::

------------------------------------------------------------------------

## Counting Letters with Sherlock Holmes {.center}

------------------------------------------------------------------------

## Sherlock Holmes: The Adventure of the Dancing Men

------------------------------------------------------------------------

## Sherlock Holmes: The Adventure of the Dancing Men

------------------------------------------------------------------------

## Nursery Rhymes with Ben Affleck {.center}

------------------------------------------------------------------------

## Who was Solomon Grundy?

------------------------------------------------------------------------

## Who was Solomon Grundy?

------------------------------------------------------------------------

## Being a Mermaid with Katie Ledecky {.center}

------------------------------------------------------------------------

## Being a Mermaid with Katie Ledecky

------------------------------------------------------------------------

## Jack and Rose lived happily ever after {.center}

------------------------------------------------------------------------

## Jack and Rose lived happily ever after

------------------------------------------------------------------------

## The Art of Surprise with Gabbar Singh {.center}

------------------------------------------------------------------------

## The Art of Surprise with Gabbar Singh
