---
date: "`r Sys.Date()`"
title: "The Art of Parallel Thinking"
author: "Arvind Venkatadri"
external_link: ""
weight: 40
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
links:
slides: ""
summary: 
tags:
- Cultural Capital
- Thinking Hats
- Edward de Bono
url_code: ""
url_pdf: "pdf/6H/KS Mathew - Six Thinking Hats.pdf"
url_slides: ""
url_video: ""
---

## Parallel Thinking

`r blogdown::shortcode("youtube", "uYBaSZYZ3sI")`


## Propositions

Let us consider a couple of ideas for schemes that have been "around" for some time:

- Military Conscription for 2 years
- Children Manage the House for one week
- Young People must be assigned one Elderly Person to live with
- All Cars must be removed from the City Centre


Some of the de Bono Thinking Tools: 

1. 6 Thinking Hats Quick Reference [(**PDF Link**)](W1D1 - 01 - The Six Thinking Hats.pdf)

2. 6H Technique - PMI: Plus Minus Interesting : [(**Web Link**)](https://www.cortthinking.com/cort/1/p-m-i-plus-minus-and-interesting-cort-1-lesson-1)

3. 6H Technique - APC: Alternatives, Possibilities, Choices: [(**Web Link**)](https://www.cortthinking.com/cort/1/alternatives-possibilities-choices-cort-1-lesson-8)

4. 6H Technique - CAF: Consider All Factors: [(**Web Link**)](https://www.cortthinking.com/cort/1/caf-consider-all-factors-cort-1-lesson-2)

5. 6H Technique - OPV: Other Peoples' Voices: [(**Web Link**)](https://www.cortthinking.com/cort/1/other-people%E2%80%99s-views-cort-1-lesson-10)

6. 6H Technique - CnS: Consequence and Sequel : [(**Web Link**)](https://www.cortthinking.com/cort/1/cs-consequence-and-sequel-cort-1-lesson-4)

## References

1. Reading in Parallel Thinking [(**Web Link**)](https://www.debonogroup.com/services/core-programs/lateral-thinking/parallel-thinking/)

2. Edward de Bono, Six Thinking Hats [(**Goodreads**)](https://www.goodreads.com/book/show/97030.Six_Thinking_Hats)


