---
title: "\U0001F576 Happy Data are all Alike"
subtitle: "Distributions"
author: "Arvind Venkatadri"
date: "`r Sys.Date()`"
weight: 20
summary: "Single Quant Variable Graphs and their Siblings"
tags:
- Qual Variables and Quant Variables
- Bar and Column Charts
- Histograms and Density Plots

image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
external_link: ""
links:
# - icon: linkedin
#   icon_pack: fab
#   name: 
#   url: https://linkedin.com/arvindvenkatadri
# - icon: twitter
#   icon_pack: fab
#   name: 
#   url: https://twitter.com/arvind_v
slides: ""
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)

```

## What graphs will we see today?

Some of the very basic and commonly used plots for data are:
- Bar and Column Charts
- Histograms and Frequency Distribution

## An Example: Bar and Column Charts


## An Example: Histograms and Frequency Distributions

## How does this Work?

Histograms are best to show the distribution of raw *quantitative data*, by displaying the number of values that fall within defined ranges, often called *buckets* or *bins*. 

Although histograms may look similar to column charts, the two are different. First, histograms show *continuous data*, and usually you can adjust the bucket ranges to explore frequency patterns. For example, you can shift histogram buckets from 0-1, 1-2, 2-3, etc. to 0-2, 2-4, etc. 
By contrast, column charts show *categorical data*, such as the number of apples, bananas, carrots, etc. Second, histograms do not usually show spaces between buckets because these are *continuous values*, while column charts show spaces to separate each *category*.


## What is the Story here?





## An Example: Frequency Density

<p align="center"><iframe src="//www.gapminder.org/tools/?embedded=true#$model$markers$mountain$encoding$frame$speed:187;;;;;&chart-type=mountain&url=v1" style="width: 100%; height: 500px; margin: 0 0 0 0; border: 1px solid grey;"allowfullscreen></iframe></p>

## What is the Story here?

Let us listen to the late Hans Rosling from the [Gapminder Project](https://www.gapminder.org), which aims at telling stories of the world with data, to remove systemic biases about poverty, income and gender related issues.


<iframe src="https://player.vimeo.com/video/127511255?h=a225cf98cc" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/127511255">How many are rich and how many are poor?</a> from <a href="https://vimeo.com/gapminder">Gapminder</a> on <a href="https://vimeo.com">Vimeo</a>.</p>


## Your Turn

1. India 
1. Old Faithful Data
1. Income data
3. Diamonds Data from R
4. calmcode.io dataset


## Fun Stuff

1. See the scrolly animation for a histogram at this website: **Exploring Histograms, an essay by Aran Lunzer and Amelia McNamara**
<https://tinlizzie.org/histograms/?s=09>

