---
title: "\U0001F4CE Correlations"
subtitle: "How one variable changes with another"
author: "Arvind Venkatadri"
date: "`r Sys.Date()`"
weight: 30
type: book
summary: "How one variable changes with another"
tags:
- Correlations  
- Scatter and Bubble Plots  
- 2D Density Plots  
- Heatmaps  
- Regression Lines  
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
external_link: ""
links:
- icon: circle
  icon_pack: fas
  name: Orange Tutorial
  url: "labs/Data-Analytics/correlations.ows"
- icon: sun
  icon_pack: fas
  name: Radiant
  url: "labs/Data-Analytics/correlations.rda"
- icon: r-project
  icon_pack: fab
  name: R Tutorial
  url: "labs/Data-Analytics/correlations.html"
- icon: database
  icon_pack: fas
  name: Sample Datasets
  url: "labs/Data-Analytics/data/qdd-data.zip"
slides: ""
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(blogdown)
library(tidyverse)
library(palmerpenguins)
library(patchwork)
library(ggridges)
library(ggformula)
library(mosaic)
library(GGally)
library(grid)

```

## What graphs will we see today?

Some of the very basic and commonly used plots for data are:

- Scatter Plot  
- Contour Plot  
- Correlogram  
- Heatmap  


## What Correlation Charts can we plot with Numerical  / Quantitative Data?

```{r charts, echo=FALSE, warning=FALSE,message=FALSE}
mpg <- mpg %>% mutate(drv= as_factor(drv))
p <- ggplot(mpg, alpha = 0.3) 
p1 <- gf_point(cty ~ hwy, fill = ~drv, colour = ~drv, data = mpg) %>% gf_smooth(method = "lm", title = "Scatter Plot with Correlation/Regression/Trend Line")
p2 <- gf_density_2d(cty~hwy, data = mpg, title = "2D Density Plot")
p1 + p2

```

```{r pairs-charts, echo=FALSE, warning=FALSE,message=FALSE}
p2 <- GGally::ggpairs(mpg, columns = c("hwy", "cty", "displ","cyl"), diag = list("densityDiag"), title = "Pairwise Correlations Plot")
p2

```

```{r cor-plot, echo=FALSE, warning=FALSE,message=FALSE}
library(corrplot)

mpg_num <- mpg %>% dplyr::select(hwy, cty, displ, cyl)
mydata_cor <- cor(mpg_num)
corrplot(mydata_cor,method = "ellipse",type = "lower",main = "Correlogram")

# Heatmap with numbers
corrplot.mixed(mydata_cor, 
               lower = "color",
               upper = "number",
               bg = "wheat",
               tl.pos = "d",
               main = "Heatmap?")


```



## Conclusion


## Your Turn





## References

1. Minimal R using `mosaic`. <https://cran.r-project.org/web/packages/mosaic/vignettes/MinimalRgg.pdf>


