---
date: "`r Sys.Date()`"
title: "TRIZ - The Laws of Evolutuon"
author: "Arvind Venkatadri"
external_link: ""
weight: 10
image:
  caption: 
  focal_point: Smart
links:
# - icon: flask
#   icon_pack: fas
#   name: TRIZ DataBase
#   url: /slides/TRIZ Database/index.html
# - icon: game
#   icon_pack: fab
#   name: Game
#   url: /pdf/TRIZ/Titanic_Case_Study.pdf
slides: 
summary: 
tags:
- TRIZ Laws of Product Evolution
- Past, Present, and Future
- Subsystem
- System
- Super-System
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

# Introduction


## References

1. TRIZ for Dummies Cheat Sheet [(weblink)](https://www.dummies.com/business/management/triz-for-dummies-cheat-sheet/)

1. TRIZ Inventive Principles in Pics @instagram: <https://www.instagram.com/stories/highlights/17857566926043828/>

1. Stan Kaplan, ***An Introduction to TRIZ***[(PDF)](pdf/TRIZ/Stan Kaplan-Intro-to-TRIZ.pdf)
This is a simple and short introduction to *all* aspects of Classical TRIZ.

1. Jack Hipple, "The Ideal Result: What it is and how to achive it", Springer, 2012.

1. Project TETRIS: Chapter 1: Introduction to Classical TRIZ [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_01.pdf)

1. Project TETRIS: Chapter 2: Laws of System Evolution [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_02.pdf)

1. Project TETRIS: Chapter 3: Short Review of ARIZ: Algorithm for Innovative Problem Solving and a Case Study [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_03.pdf)

1. Project TETRIS: Chapter 4: Substance-Field ( "Su-Field" ) Analysis and Standard Solutions basic notions and rules [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_04.pdf)

1. Project TETRIS: Chapter 5: Techniques  to  Resolve  Contradictions / Resources / Effects [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_05.pdf)

1. Project TETRIS: Examples of inventive problems: Example 1-5 [(RAR Archive File)](https://innovazionesistematica.it/wp-content/uploads/2020/10/ExamplesEN.rar)
