---
date: "`r Sys.Date()`"
title: "TRIZ - The Unreasonable Effectiveness of Available Resources"
author: "Arvind Venkatadri"
external_link: ""
weight: 70
image:
  caption: 
  focal_point: Smart
links:
# - icon: flask
#   icon_pack: fas
#   name: TRIZ DataBase
#   url: /slides/TRIZ Database/index.html
# - icon: game
#   icon_pack: fab
#   name: Game
#   url: /pdf/TRIZ/Titanic_Case_Study.pdf
slides: 
summary: "This Module is part of a Creative Problem Solving course I offer at Srishti Manipal Institute, Bangalore"
tags:
- Available Resources
- Functional Fixedness
- Assumptions

url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

# Introduction

In the previous Module on **Problems and Contradictions** we understood how to identify a **Technical Contradiction** in everyday situations. This is the first and most important step in the TRIZ Problem Solving Method. 

Another important idea in TRIZ is that of **Available Resources**. Let us appreciate this idea with the help of two games. 

## Available Resources: Game #1  

You have to Stick the lighted candle to the Wall in such a way that the melting wax does not drop on to the floor. 


## Available Resources: Game #2

Look at the graph below: does it remind you of something you know very well?

```{r echo=FALSE, message=FALSE}
# Reference: https://rkabacoff.github.io/datavis/Other.html
library(readr)
# data("Titanic")

# summarize data
# library(dplyr)
# titanic_table <- Titanic %>%
#   as_tibble() %>% 
#   group_by(Class, Sex, Survived) %>%
#   count()
# 
# titanic_table$Survived <- factor(titanic_table$Survived, 
#                                  levels = c("Yes", "No"))

# Alluvial Plot
library(ggplot2)
library(ggalluvial)

# ggplot(titanic_table,
#        aes(axis1 = Class,
#            axis2 = Survived,
#            y = n)) +
#   geom_alluvium(aes(fill = Sex)) +
#   geom_stratum() +
#   geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
#             #label.strata = TRUE) +
#   scale_x_discrete(limits = c("Class", "Survived"),
#                    expand = c(.1, .1)) +
#   # labs(title = "Titanic data",
#   #      subtitle = "stratified by class, sex, and survival",
#   #      y = "Frequency") +
#   theme_minimal()

# ggplot(titanic_table,
#        aes(axis1 = Class,
#            axis2 = Sex,
#            axis3 = Survived,
#            y = n)) +
#   geom_alluvium(aes(fill = Class)) +
#   geom_stratum() +
#   geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
#             #label.strata = TRUE) +
#   scale_x_discrete(limits = c("Class", "Sex", "Survived"),
#                    expand = c(.1, .1)) +
#   scale_fill_viridis_d() +
#   # labs(title = "Titanic data",
#   #      subtitle = "stratified by class, sex, and survival",
#   #      y = "Frequency") +
#   theme_minimal() +
#   theme(legend.position = "none") 
#   
#####################################
titanic_wide <- data.frame(Titanic)
#head(titanic_wide)
#>   Class    Sex   Age Survived Freq
#> 1   1st   Male Child       No    0
#> 2   2nd   Male Child       No    0
#> 3   3rd   Male Child       No   35
#> 4  Crew   Male Child       No    0
#> 5   1st Female Child       No    0
#> 6   2nd Female Child       No    0
ggplot(data = titanic_wide,
       aes(axis1 = Class, axis2 = Sex, axis3 = Age,
           y = Freq)) +
  scale_x_discrete(limits = c("Class", "Sex", "Age"), 
                   expand = c(.2, .05)) +
  xlab("Demographic") + ylab("No. of  People") +
  geom_alluvium(aes(fill = Survived),curve_type = "arctangent") +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_classic()

```
What does this graph represent?

Let us pretend we are part of this graph and see where our Problem Formulating Skills take us!


# Discussion

- Problems and Contradictions
- All Available Resources 
- **Assumptions** and **Functional Fixedness**

> A comparable switch of attention occurs in an old joke about a worker in a high security factory, in which the employees were carefully watched when they left at the end of their work day. On a particular day, this worker was stopped at the factory gate as he walked out with a wheelbarrow full of styrofoam packing peanuts. He explained that he had salvaged these from the trash, and was planning to use them in shipping gifts to his grandchildren. Searching through this packing material, the guards found nothing, and so they let the man go home. The following week the same thing happened, and the worker was again stopped. But he offered the very same story, and when the guards searched through the packing peanuts and found nothing, he was allowed to leave. But this continued, week after week, until the guards could no longer believe that one person would want or could make use of so much packing material. Finally, the man was held for interrogation, at which time he admitted that he had absolutely no use for packing peanuts - and that, all these weeks, he had been stealing wheelbarrows.

>Hearing this joke, I am reminded of the phrase “part and parcel”, which is a rough equivalent of <u>[**“figure and ground”**](https://www.interaction-design.org/literature/article/the-laws-of-figure-ground-praegnanz-closure-and-common-fate-gestalt-principles-3)</u>. Throughout most of it, the packing peanuts occupy center stage as figure (part), while the wheelbarrows (which function merely as containers) are completely ignored as innocuous ground (parcel). At the end of the joke, there is an unexpected twist, a switch of emphasis, a recentering, when we learn that the ***parcel is really the part***. 

This should also remind us of the Guilford Alternative Uses Exercise that we did, where we forced ourselves to leave the "regular use" of an object behind and think of it as serving quite another function.

## References

1. Resources Game [(PDF)](pdf/TRIZ/Titanic_Case_Study.pdf)

1. Stan Kaplan, ***An Introduction to TRIZ***[(PDF)](pdf/TRIZ/Stan Kaplan-Intro-to-TRIZ.pdf)
This is a simple and short introduction to *all* aspects of Classical TRIZ.

1. Jack Hipple, "The Ideal Result: What it is and how to achieve it", Springer, 2012.
