---
title: "07-Network Data and Visualization in R"
subtitle: ""  
author: "Arvind Venkatadri"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: ["default", "css/ohsu.css", "css/ohsu-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      slideNumberFormat: "%current%"
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
library("xaringanthemer")
library("xaringanExtra")
library("tidyverse")
########################################
# Network Analysis Library (Handle data and Viz)
library("igraph")
library("netrankr")
########################################
# For Network "Manipulation"
library("tidygraph")
# For Network Visualization
library("ggraph")
library("graphlayouts")
# For "Network" Datasets
library("igraphdata")

# For Dynamic Network Visualization
library("network") 
library("sna")
library("visNetwork")
library("threejs")
library("ndtv")
library("networkD3")
library("animation")
library("maps")
library("geosphere")
```

```{r xaringanExtra, include=FALSE}
use_webcam()
use_fit_screen()
use_panelset()
use_broadcast()
use_extra_styles(hover_code_line = TRUE,mute_unhighlighted_code = FALSE)
```

# Introduction




---

# What is a Network?




---

