---
date: "`r Sys.Date()`"
title: "TRIZ - The Ideal Final Result"
author: "Arvind Venkatadri"
external_link: ""
weight: 75
image:
  caption: 
  focal_point: Smart
links:
# - icon: flask
#   icon_pack: fas
#   name: TRIZ DataBase
#   url: /slides/TRIZ Database/index.html
# - icon: game
#   icon_pack: fab
#   name: Game
#   url: /pdf/TRIZ/Titanic_Case_Study.pdf
slides: 
summary: "This Module is part of a Creative Problem Solving course I offer at Srishti Manipal Institute, Bangalore"
tags:
- Ideal Final Result
- 

url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

# Introduction

In the previous Module on **Available Resources** we understood how to identify resources in everyday situations and to come to terms with our assumptions and **functional fixedness**. This is the first and most important step in the TRIZ Problem Solving Method. 

Another important idea in TRIZ is that of the **Ideal Final Result(IFR)**. 


## Ideal Final Result: Game
TBD





# Discussion

Like in Alice in Wonderland, it is important to conceptualize the Ideal Final Result as one of the **six impossible things before breakfast**(<http://www.literaturepage.com/read/throughthelookingglass-42.html>). As Jack Hipple says in his book *The Ideal Result* ( Reference 3), **it's when something performs its function, and does not exist.** In this sense, TRIZ is a foretaste of what was said later, that the [Best Technologies are those that disappear](https://web.archive.org/web/20141022035044/http://www.ubiq.com/hypertext/weiser/SciAmDraft3.html) 
<https://web.archive.org/web/20141022035044/http://www.ubiq.com/hypertext/weiser/SciAmDraft3.html>



- Ideal Final Result ( IFR )


## Case Studies 

(Move this to Slides soon!!)

1. Pizza Box (https://www.metodolog.ru/triz-journal/archives/2008/03/04/)

1.


1.



## References

1. Titanic Game [(PDF)](pdf/TRIZ/Titanic_Case_Study.pdf)

1. Stan Kaplan, ***An Introduction to TRIZ***[(PDF)](pdf/TRIZ/Stan Kaplan-Intro-to-TRIZ.pdf)
This is a simple and short introduction to *all* aspects of Classical TRIZ.

1. Jack Hipple, "The Ideal Result: What it is and how to achieve it", Springer, 2012.
