---
date: "2021-10-25"
title: "Introduction to TRIZ"
external_link: ""
weight: 5
image:
  caption: 
  
  focal_point: Smart
links:
- icon: flask
  icon_pack: fas
  name: TRIZ DataBase
  url: /slides/TRIZ Database/index.html
- icon: game
  icon_pack: fab
  name: Game
  url: /pdf/TRIZ/Titanic_Case_Study.pdf
slides: 
summary: 
tags:
- Contradictions
- Contradiction Matrix
- 39 TRIZ Parameters
- 40 Inventive Principles
- Genrikh Altshuller
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

# Introduction

In the previous Module on **Problems and Contradictions** we understood how to identify a **Technical Contradiction** in everyday situations. This is the first and most important step in the TRIZ Problem Solving Method. 

Next we look at two methods to **Resolve Contradictions**:

- Using the **Contradiction Matrix** and **Inventive Principles**

- Using TRIZ **Separation Principles**



## Project TETRIS TRIZ Videos
Let us get an actual experience of TRIZ methods with these short videos:


1. History of TRIZ   
  `r blogdown::shortcode("youtube", "NeDAnftRx8c")`<br>


2. TRIZ Tales: Nina at School   
  `r blogdown::shortcode("youtube", "ouWWuwW21ZI")` <br>

3. TRIZ Tales: Nina at University   
  `r blogdown::shortcode("youtube", "MxOGaB4OgYc")` <br>

4. TRIZ Tales: Nina at Work #1 
  `r blogdown::shortcode("youtube", "bXxMf4AX_lE")` <br>

5. TRIZ Tales: Nina at Work #2 
  `r blogdown::shortcode("youtube", "J_O3yR2kk2Q")` <br>


6. How to use the Contradiction Matrix:[(Coursera Video)](https://www.coursera.org/lecture/creative-thinking-techniques-and-tools-for-success/contradiction-matrix-DtEKz>)


7. The TRIZ Contradiction Matrix (2003) [(Matrix)](pdf/TRIZ/TRIZ_interactive_contradiction_matrix_2016.xlsx)


## Game Plan # 2

Let us play two Games to motivate the philosophy of TRIZ-oriented thinking and to obtain an understanding of its main ideas:  

- Problems and Contradictions
- Ideal Final Result ( IFR )
- All Available Resources  
- Contradiction Matrix and the 39 (Metaphorical) Parameters  
- 40 Inventive Principles  

2. Titanic Game [(PDF)](pdf/TRIZ/Titanic_Case_Study.pdf)


## Case Studies (Move this to Slides soon!!)

1. Pizza Box (https://www.metodolog.ru/triz-journal/archives/2008/03/04/)

1.


1.



## References

1. TRIZ Inventive Principles in Pics @instagram: <https://www.instagram.com/stories/highlights/17857566926043828/>

1. Stan Kaplan, ***An Introduction to TRIZ***[(PDF)](pdf/TRIZ/Stan Kaplan-Intro-to-TRIZ.pdf)
This is a simple and short introduction to *all* aspects of Classical TRIZ.

1. Jack Hipple, "The Ideal Result: What it is and how to achive it", Springer, 2012.

1. Project TETRIS: Chapter 1: Introduction to Classical TRIZ [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_01.pdf)

1. Project TETRIS: Chapter 2: Laws of System Evolution [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_02.pdf)

1. Project TETRIS: Chapter 3: Short Review of ARIZ: Algorithm for Innovative Problem Solving and a Case Study [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_03.pdf)

1. Project TETRIS: Chapter 4: Substance-Field ( "Su-Field" ) Analysis and Standard Solutions basic notions and rules [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_04.pdf)

1. Project TETRIS: Chapter 5: Techniques  to  Resolve  Contradictions / Resources / Effects [(PDF)](https://innovazionesistematica.it/wp-content/uploads/2020/10/EN_05.pdf)

1. Project TETRIS: Examples of inventive problems: Example 1-5 [(RAR Archive File)](https://innovazionesistematica.it/wp-content/uploads/2020/10/ExamplesEN.rar)
